
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ejemplo_hoc2;

/** CUP generated class containing symbol constants. */
public class AnalizadorSintacticoSym {
  /* terminals */
  public static final int DecrementoDiv = 13;
  public static final int OpSuma = 2;
  public static final int ParIzq = 14;
  public static final int GE = 35;
  public static final int UMINUS = 31;
  public static final int OpAsig = 6;
  public static final int AumentoProd = 12;
  public static final int CASE = 22;
  public static final int SEMIC = 16;
  public static final int Decremento = 9;
  public static final int CONTINUE = 26;
  public static final int FOR = 25;
  public static final int OpPotencia = 7;
  public static final int LLAVE_IZQ = 41;
  public static final int NOT = 40;
  public static final int AND = 33;
  public static final int LT = 36;
  public static final int OR = 32;
  public static final int CONST_PRED = 29;
  public static final int DOS_P = 43;
  public static final int Aumento = 8;
  public static final int NUM = 27;
  public static final int IF = 19;
  public static final int LE = 37;
  public static final int EOF = 0;
  public static final int OpProd = 4;
  public static final int ParDer = 15;
  public static final int error = 1;
  public static final int BREAK = 24;
  public static final int EQ = 38;
  public static final int SWITCH = 21;
  public static final int ELSE = 20;
  public static final int LLAVE_DER = 42;
  public static final int DecrementoRes = 11;
  public static final int BLTIN = 30;
  public static final int WHILE = 18;
  public static final int DEFAULT = 23;
  public static final int AumentoSum = 10;
  public static final int NE = 39;
  public static final int OpResta = 3;
  public static final int GT = 34;
  public static final int VAR = 28;
  public static final int PRINT = 17;
  public static final int OpDiv = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OpSuma",
  "OpResta",
  "OpProd",
  "OpDiv",
  "OpAsig",
  "OpPotencia",
  "Aumento",
  "Decremento",
  "AumentoSum",
  "DecrementoRes",
  "AumentoProd",
  "DecrementoDiv",
  "ParIzq",
  "ParDer",
  "SEMIC",
  "PRINT",
  "WHILE",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "FOR",
  "CONTINUE",
  "NUM",
  "VAR",
  "CONST_PRED",
  "BLTIN",
  "UMINUS",
  "OR",
  "AND",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "NOT",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "DOS_P"
  };
}

